name: "shuttle-core"
description: "Shuttle Core is a free open-source library"

baseurl: "http://shuttle.github.io/shuttle-core"

paginate: 10

permalink: pretty
pygments: true

markdown: redcarpet
redcarpet:
  extensions: ["tables"]